### ISSUE TITLE
CC field not supported

### ISSUE THREAD

**Issue by richja** [vineetchoudhary/mailgun-action#10]
When I try to use cc field for carbon copy, I get following warning:
`Unexpected input(s) 'cc', valid inputs are ['api-key', 'domain', 'to', 'from', 'subject', 'body']`

The rest is working fine, just the email is not sent to recipient in cc.

Defined as follow:
```
steps:
      - name: Send Mail Action
        id: sendmail
        uses: vineetchoudhary/mailgun-action@v1.0
        with:
          api-key: ${{ secrets.MAILGUN_API_SECRET }}
          domain: ${{ secrets.MAILGUN_DOMAIN }}
          from: ${{ secrets.FROM }}
          to: ${{ secrets.RECIPIENT }}
          cc: ${{ secrets.CARBON_COPY }}
          subject: test
          body: test
```

Action run in question:
https://github.com/richja/tks-mapa/actions/runs/375394306
